---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenyu.
--- DateTime: 2022/4/27 20:03
---

local Instatiate = CS.UnityEngine.GameObject.Instantiate

xlua.hotfix(CS.Treasour,'CreatePrize',function(self)
    for i = 1, 4 do
        local go = Instatiate(self.gold,self.transform.position + CS.UnityEngine.Vector3(-10 + i*100,0,0),self.transform.rotation)
        go.transform:SetParent(self.cavas)
        local go1 = Instatiate(self.diamands,self.transform.position + CS.UnityEngine.Vector3(0,100,0)+CS.UnityEngine.Vector3(-10 + i*100,0,0),self.transform.rotation)
        go1.transform:SetParent(self.cavas)
    end
end)

xlua.private_accessible(CS.Gun)

xlua.hotfix(CS.Gun,'Attack',function(self)

    if self.gold < 1 + (self.gunLevel - 1) * 2 then
        return
    end
    
    if CS.UnityEngine.Input.GetMouseButtonDown(0) then
        self.bullectAudio.clip = self.bullectAudios[self.gunLevel - 1];
        self.bullectAudio:Play();
        if self.Butterfly then
            CS.UnityEngine.GameObject.Instantiate(self.Bullects[self.gunLevel - 1], self.attackPos.position, self.attackPos.rotation * CS.UnityEngine.Quaternion.Euler(0, 0, 20));
            CS.UnityEngine.GameObject.Instantiate(self.Bullects[self.gunLevel - 1], self.attackPos.position, self.attackPos.rotation * CS.UnityEngine.Quaternion.Euler(0, 0, -20));
        end
        CS.UnityEngine.GameObject.Instantiate(self.Bullects[self.gunLevel - 1], self.attackPos.position, self.attackPos.rotation);

        if not self.canShootForFree then
            self:GoldChange(-1 - (self.gunLevel - 1) * 2)
        end
        self.attackCD = 0
        self.attack = false
    end
end)