---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenyu.
--- DateTime: 2022/4/27 20:03
---

xlua.hotfix(CS.Treasour,'CreatePrize',nil)
xlua.hotfix(CS.Gun,'Attack',nil)
xlua.hotfix(CS.Gun,'GoldChange',nil)
xlua.hotfix(CS.Gun,'DiamandsChange',nil)
xlua.hotfix(CS.Ice,'Start', nil)
xlua.hotfix(CS.Fire,'Start', nil)
xlua.hotfix(CS.ButterFly,'Start', nil)
xlua.hotfix(CS.Boss,'Start', nil)
xlua.hotfix(CS.DeffendBoss,'Start', nil)
xlua.hotfix(CS.InvisibleBoss,'Start', nil)
xlua.hotfix(CS.CreateFish,'Update',nil)
xlua.hotfix(CS.Fish,'TakeDamage',nil)
xlua.hotfix(CS.Boss,'TakeDamage',nil)
xlua.hotfix(CS.Gun,'RotateGun',nil)
xlua.hotfix(CS.GunImage,'RotateGun',nil)

